/**
 * «Copyright 2025 Roberto Reinosa Fernández»
 * 
 * This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

package com.RRF.nseqverify;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author Roberto Reinosa Fernández
 */

public class Interfaz extends javax.swing.JFrame {

    public static String entrada;
    public static String salida;
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/com/RRF/nseqverify/Logo_NSeqVerify.png")).getImage());
        
        setLocationRelativeTo(null);      
   
        setTitle("NSeqVerify 0.0.1");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogEntrada2 = new javax.swing.JDialog();
        jFileChooser3 = new javax.swing.JFileChooser();
        DialogSalida = new javax.swing.JDialog();
        jFileChooser4 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        DialogEntrada2.setSize(new java.awt.Dimension(1000, 500));

        jFileChooser3.setMaximumSize(new java.awt.Dimension(1000, 500));
        jFileChooser3.setMinimumSize(new java.awt.Dimension(1000, 500));
        jFileChooser3.setPreferredSize(new java.awt.Dimension(1000, 500));
        jFileChooser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser3ActionPerformed(evt);
            }
        });
        DialogEntrada2.getContentPane().add(jFileChooser3, java.awt.BorderLayout.CENTER);

        DialogSalida.setSize(new java.awt.Dimension(1000, 500));

        jFileChooser4.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooser4.setMaximumSize(new java.awt.Dimension(1000, 500));
        jFileChooser4.setMinimumSize(new java.awt.Dimension(1000, 500));
        jFileChooser4.setPreferredSize(new java.awt.Dimension(1000, 500));
        jFileChooser4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser4ActionPerformed(evt);
            }
        });
        DialogSalida.getContentPane().add(jFileChooser4, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 520));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 520));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 520));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 123, 255));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Input");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 30, 120, 35);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Input File:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 20, 150, 17);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(136, 136, 136));
        jLabel2.setText("No file selected");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 50, 380, 16);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Calculation Type:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 80, 150, 17);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Min. Qual.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 160, 160, 17);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(230, 190, 60, 24);

        jButton3.setBackground(new java.awt.Color(40, 167, 69));
        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(254, 254, 254));
        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 440, 160, 35);

        jButton2.setBackground(new java.awt.Color(220, 53, 69));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(254, 254, 254));
        jButton2.setText("Cancel");
        jButton2.setMaximumSize(new java.awt.Dimension(67, 28));
        jButton2.setMinimumSize(new java.awt.Dimension(67, 28));
        jButton2.setPreferredSize(new java.awt.Dimension(67, 28));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 440, 160, 35);

        jButton4.setBackground(new java.awt.Color(0, 123, 255));
        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(254, 254, 254));
        jButton4.setText("Output");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(30, 380, 120, 35);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(136, 136, 136));
        jLabel4.setText("No file selected");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 400, 450, 16);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Output File:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 370, 150, 17);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Max. Reads");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 160, 160, 17);

        jComboBox3.setBackground(new java.awt.Color(254, 254, 254));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Preprocess FASTQ", "Assemble", "Classify nt", "Classify aa" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(30, 110, 340, 34);

        jTextField2.setText("20");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(30, 190, 70, 24);

        jCheckBox3.setFont(new java.awt.Font("Ubuntu Sans", 1, 15)); // NOI18N
        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Rev.");
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(320, 190, 120, 24);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText("Trim Ends");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 160, 160, 17);

        jTextField3.setText("10");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(130, 190, 70, 24);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setText("K-MERS");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 230, 160, 17);

        jTextField6.setText("21;33;45;55;65");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(30, 260, 60, 24);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setText("Min. k-mer Freq.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(120, 230, 160, 17);

        jTextField7.setText("5");
        jPanel1.add(jTextField7);
        jTextField7.setBounds(120, 260, 110, 24);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setText("Min. Contig");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(270, 230, 160, 17);

        jTextField8.setText("200");
        jPanel1.add(jTextField8);
        jTextField8.setBounds(260, 260, 100, 24);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setText("Tip Thres.");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 300, 160, 17);

        jTextField9.setText("2");
        jPanel1.add(jTextField9);
        jTextField9.setBounds(30, 330, 70, 24);

        jTextField10.setText("250");
        jPanel1.add(jTextField10);
        jTextField10.setBounds(120, 330, 90, 24);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel14.setText("Max. Bubble");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(120, 300, 160, 17);

        jTextField11.setText("2.0");
        jPanel1.add(jTextField11);
        jTextField11.setBounds(240, 330, 120, 24);

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel15.setText("Bubble Coverage");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(240, 300, 160, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DialogEntrada2.setLocationRelativeTo(null);
        DialogEntrada2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        jButton3.setEnabled(false);
        
        if(jComboBox3.getSelectedIndex() == 1){
            
            HiloPreprocesadorFASTQ preprocesarFASTQ = new HiloPreprocesadorFASTQ(entrada, salida, Integer.parseInt(jTextField2.getText()), Integer.parseInt(jTextField3.getText()), Integer.parseInt(jTextField1.getText()), jCheckBox3.isSelected());
            
        }else if(jComboBox3.getSelectedIndex() == 2){
                        
            HiloEnsamblador ensamblador = new HiloEnsamblador(entrada, salida, jTextField6.getText(), Integer.parseInt(jTextField7.getText()),
            Integer.parseInt(jTextField8.getText()), Integer.parseInt(jTextField9.getText()), Integer.parseInt(jTextField10.getText()),
            Double.parseDouble(jTextField11.getText()));
            
            
        }else if(jComboBox3.getSelectedIndex() == 3){
        
           HiloClasificador clasificador = new HiloClasificador(entrada, salida);
        
        }else if(jComboBox3.getSelectedIndex() == 4){
            
            HiloClasificadorProteinas clasificadorP = new HiloClasificadorProteinas(entrada, salida);
            
        }else if(jComboBox3.getSelectedIndex() == 0){
            
            jButton3.setEnabled(true);
            
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        CancelarHilos.cancelarHilos();
        jButton3.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        DialogSalida.setLocationRelativeTo(null);
        DialogSalida.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed

        
        if(jComboBox3.getSelectedIndex() == 0){
            
            jTextField1.setEnabled(true);
            jTextField2.setEnabled(true);
            jTextField3.setEnabled(true);
            jCheckBox3.setEnabled(true);
            
            jTextField6.setEnabled(true);
            jTextField7.setEnabled(true);
            jTextField8.setEnabled(true);
            jTextField9.setEnabled(true);
            jTextField10.setEnabled(true);
            jTextField11.setEnabled(true);
            
        }else if(jComboBox3.getSelectedIndex() == 1){
            
            jTextField1.setEnabled(true);
            jTextField2.setEnabled(true);
            jTextField3.setEnabled(true);
            jCheckBox3.setEnabled(true);
            
            jTextField6.setEnabled(false);
            jTextField7.setEnabled(false);
            jTextField8.setEnabled(false);
            jTextField9.setEnabled(false);
            jTextField10.setEnabled(false);
            jTextField11.setEnabled(false);
            
        }else if(jComboBox3.getSelectedIndex() == 2){
            
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField3.setEnabled(false);
            jCheckBox3.setEnabled(false);
            
            jTextField6.setEnabled(true);
            jTextField7.setEnabled(true);
            jTextField8.setEnabled(true);
            jTextField9.setEnabled(true);
            jTextField10.setEnabled(true);
            jTextField11.setEnabled(true);
            
        }else if(jComboBox3.getSelectedIndex() == 3 || jComboBox3.getSelectedIndex() == 4){
            
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField3.setEnabled(false);
            jCheckBox3.setEnabled(false);
            
            jTextField6.setEnabled(false);
            jTextField7.setEnabled(false);
            jTextField8.setEnabled(false);
            jTextField9.setEnabled(false);
            jTextField10.setEnabled(false);
            jTextField11.setEnabled(false);
                
        }
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jFileChooser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser3ActionPerformed

        String command = evt.getActionCommand();

        if(command.equals(JFileChooser.APPROVE_SELECTION)){

            String ruta = String.valueOf(jFileChooser3.getSelectedFile()) + "/";

            entrada = ruta;

            String rutaSalida = "... ";

            if(ruta.length() <= 25){

                rutaSalida = ruta;

            }else{

                for(int i = ruta.length()- 25; i < ruta.length(); i++){

                    rutaSalida += ruta.toCharArray()[i];

                }

            }

            jLabel2.setText(rutaSalida);

            DialogEntrada2.dispose();

        }else if(command.equals(JFileChooser.CANCEL_SELECTION)){

            DialogEntrada2.dispose();

        }
    }//GEN-LAST:event_jFileChooser3ActionPerformed

    private void jFileChooser4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser4ActionPerformed

        String command = evt.getActionCommand();

        if(command.equals(JFileChooser.APPROVE_SELECTION)){

            String ruta = String.valueOf(jFileChooser4.getSelectedFile()) + "/";

            salida = ruta;

            String rutaSalida = "... ";

            if(ruta.length() <= 25){

                rutaSalida = ruta;

            }else{

                for(int i = ruta.length()- 25; i < ruta.length(); i++){

                    rutaSalida += ruta.toCharArray()[i];

                }

            }

            jLabel4.setText(rutaSalida);

            DialogSalida.dispose();

        }else if(command.equals(JFileChooser.CANCEL_SELECTION)){

            DialogSalida.dispose();

        }

    }//GEN-LAST:event_jFileChooser4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
       
        
        
        UIManager.setLookAndFeel(new NimbusLookAndFeel());
        
        UIManager.put("TextField[Focused].borderPainter", new Color(255, 255, 255));
        UIManager.put("nimbusSelectionBackground", new Color(255, 255, 255));
                        
        UIManager.put("controlShadow", new Color(255, 255, 255));
        UIManager.put("control",new Color(255, 255, 255));
        UIManager.put("nimbusSelectionBackground", new Color(233, 84, 32));
        UIManager.put("nimbusFocus", new Color(230, 230, 230));
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Thread.setDefaultUncaughtExceptionHandler((thread, throwable) -> {
            
            System.err.println("Excepción no controlada en hilo " + thread.getName() + ": " + throwable);

            if (throwable instanceof OutOfMemoryError) {
                
                System.err.println("⚠️ Error crítico de memoria detectado, intentando recuperación...");

                // Liberar memoria
                
                System.gc();

                // Interrumpir todos los hilos excepto el principal y del sistema
                
                SafeThreadKiller.interruptAllExceptCurrentAndSystem();

                // Pausa breve para dejar que los hilos terminen
                
                try { Thread.sleep(500); } catch (InterruptedException ignored) {}

                // Reactivar el botón jButton3 en la interfaz
                
                SwingUtilities.invokeLater(() -> {
                    
                    if (Interfaz.jButton3 != null) {
                        
                        Interfaz.jButton3.setEnabled(true);
                        
                        System.out.println("✅ jButton3 reactivado tras error crítico.");
                        
                    }
                    
                });
                
            } else {
                
                // Para cualquier otra excepción no controlada
                System.err.println("Error no controlado: " + throwable.getMessage());
                Interfaz.jButton3.setEnabled(true);
                
            }
            
        });
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogEntrada2;
    private javax.swing.JDialog DialogSalida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JFileChooser jFileChooser3;
    private javax.swing.JFileChooser jFileChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
